version: "3.8"
services:
  nginx:
    build:
      dockerfile: ./nginx.dockerfile
      context: .
    image: nginx
    container_name: nginx
    ports:
      - "8089:80"
    depends_on:
      - app
      
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/my-app
    ports:
      - "8081:3000"
    expose:
      - 8081
    image: app:reacts
    container_name: react_container
    command: npm start
